export {
  CustomInputAutoMultiple,
  CustomInputAutoMultiple as CustomInputAutocompleteMultipleSignal,
  CustomInputAutoComplete,
  CustomInputAutoComplete as CustomInputAutocompleteSignal,
  CustomInputCheckSignal,
  CustomInputCurrencySignal,
  CustomInputDateSignal,
  CustomInputDateTimeNative,
  CustomInputDateTimeSignal,
  CustomInputDecimal,
  CustomInputDecimal as CustomInputDecimalSignal,
  CustomInputFile,
  CustomInputFile as CustomInputFileSignal,
  CustomInputHour,
  CustomInputHour as CustomInputHourSignal,
  CustomInputImg,
  CustomInputImg as CustomInputImgSignal,
  CustomInputMaskSignal,
  CustomInputMonth,
  CustomInputMonth as CustomInputMonthSignal,
  CustomInputMultiselectSignal,
  CustomInputNgSelect,
  CustomInputNgSelect as CustomInputNgSelectSignal,
  CustomInputNumberSignal,
  CustomInputPassword,
  CustomInputPassword as CustomInputPasswordSignal,
  CustomInputPhonePrefix,
  CustomInputRemoteAutocomplete,
  CustomInputRemoteAutocomplete as CustomInputRemoteAutocompleteSignal,
  CustomInputSelectBool,
  CustomInputSelectBool as CustomInputSelectBoolSignal,
  CustomInputSelectPrefix,
  CustomInputSelectPrefix as CustomInputSelectPrefixSignal,
  CustomInputSelectSignal,
  CustomInputSwitch,
  CustomInputSwitch as CustomInputSwitchSignal,
  CustomInputTextSignal,
  CustomInputTextAreaSignal,
  CustomInputTextAreaSignal as CustomInputTextareaSignal,
  CustomInputTime,
  CustomInputTime as CustomInputTimeSignal,
  CustomInputTransferList,
  CustomInputTransferList as CustomInputTransferListSignal,
  SubirPdf,
  SubirPdf as CustomInputUploadPdfSignal,
  CustomInputUrl,
  CustomInputUrl as CustomInputUrlSignal,
  CustomSearchInput,
  CustomSearchInput as CustomSearchInputSignal,
} from "./web-inputs.impl";
