import { EApplicationRole } from "src/app/core/enums/asp-net-roles.enum";
import { ISettingsMenuItem } from "src/app/core/interfaces/menu.model";
import { AspRoleService } from "src/app/core/services/asp-role.service";

export const settingMenu = (aspRoleS: AspRoleService): ISettingsMenuItem[] => [
  {
    group: "Seguridad y Permisos",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Clientes",
    icon: "pi pi-building",
    routerLink: "/settings/clientes",
  },
  {
    group: "Seguridad y Permisos",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Usuarios",
    icon: "pi pi-user",
    routerLink: "/settings/application-user",
  },
  {
    group: "Seguridad y Permisos",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Roles",
    routerLink: "/settings/roles",
    icon: "pi pi-shield",
  },
  {
    group: "Seguridad y Permisos",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Modulos",
    routerLink: "/settings/module-app",
    icon: "pi pi-th-large",
  },
  {
    group: "Seguridad y Permisos",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Modulos | Clientes",
    routerLink: "/settings/customer-modul",
    icon: "pi pi-th-large",
  },
  {
    group: "Seguridad y Permisos",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Modulos | Roles",
    routerLink: "/settings/module-app-rol",
    icon: "pi pi-key",
  },
  {
    group: "Seguridad y Permisos",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Jerarquia de Aprobacion",
    routerLink: "/settings/approval-rules",
    icon: "pi pi-sitemap",
  },
  {
    group: "Catalogos Generales",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Bancos",
    routerLink: "/settings/banks",
    icon: "pi pi-building-columns",
  },
  {
    group: "Catalogos Generales",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Forma de pago",
    routerLink: "/settings/forma-pago",
    icon: "pi pi-credit-card",
  },
  {
    group: "Catalogos Generales",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Metodo de pago",
    routerLink: "/settings/metodo-pago",
    icon: "pi pi-wallet",
  },
  {
    group: "Catalogos Generales",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Uso de cfdi",
    routerLink: "/settings/uso-cfdi",
    icon: "pi pi-receipt",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Categorias ticket",
    routerLink: "/settings/ticket-group-category",
    icon: "pi pi-tag",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Categoria Medidor",
    routerLink: "/settings/meter-category",
    icon: "pi pi-stopwatch",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Categoria productos",
    routerLink: "/settings/product-category",
    icon: "pi pi-shopping-bag",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Clasificacion equipos",
    routerLink: "/settings/machinery-classification",
    icon: "pi pi-cog",
  },
  {
    group: "Catalogos Generales",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Unidades de medida",
    routerLink: "/settings/units-of-measurement",
    icon: "pi pi-sliders-h",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Entrega Recepcion",
    routerLink: "/settings/entrega-recepcion-cliente",
    icon: "pi pi-users",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Calendario maestro mtto",
    routerLink: "/calendars/maintenance-master",
    icon: "pi pi-calendar",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Calendario maestro Clasificacion",
    routerLink: "/calendars/team-master-calendar",
    icon: "pi pi-calendar",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Catalogo de amenidades",
    routerLink: "/settings/catalog-asset",
    icon: "pi pi-star",
  },
  // {
  //   group: "Catalogos de Tickets y Mantenimiento",
  //   visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
  //   label: "Catalogo de Permisos",
  //   routerLink: "/settings/request-types-list",
  //   icon: "pi pi-pencil",
  // },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Catalogo de inspecciones",
    routerLink: "/settings/inspection-reviews-catalog",
    icon: "pi pi-search",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Catalogo de tareas",
    routerLink: "/recurring-tasks",
    icon: "pi pi-clipboard",
  },
  // {
  //   group: "Catalogos de Tickets y Mantenimiento",
  //   visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
  //   label: "Organigramas",
  //   routerLink: "/organization-chart/view",
  //   icon: "pi pi-sitemap",
  // },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Base de Conocimiento IA",
    routerLink: "/settings/ai-knowledge-base",
    icon: "pi pi-sparkles",
  },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Configuracion Aspel",
    routerLink: "/settings/aspel-customer-empresa",
    icon: "pi pi-cog",
  },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Sincronizacion Aspel",
    routerLink: "/settings/aspel-sync",
    icon: "pi pi-sync",
  },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Conciliacion juntas mensuales",
    routerLink: "/settings/juntas-mensuales-conciliacion",
    icon: "pi pi-link",
  },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Checklist asamblea",
    routerLink: "/settings/asamblea-checklist-catalog",
    icon: "pi pi-list-check",
  },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Jobs",
    routerLink: "/settings/jobs",
    icon: "pi pi-briefcase",
  },
  {
    group: "Configuracion de Correo Electronico",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Emails corporativos",
    routerLink: "/settings/customer-data-company",
    icon: "pi pi-envelope",
  },
  {
    group: "Configuracion de Correo Electronico",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Datos de email",
    routerLink: "/settings/datos-email",
    icon: "pi pi-envelope",
  },
  {
    group: "Recursos Humanos",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Tipos de incidencia",
    routerLink: "/settings/incident-types",
    icon: "pi pi-exclamation-triangle",
  },
  {
    group: "Recursos Humanos",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Tipos de sancion",
    routerLink: "/settings/sanction-types",
    icon: "pi pi-clipboard",
  },
  {
    group: "Recursos Humanos",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Ajuste balance",
    routerLink: "/recursos-humanos/admin-balances-vacaciones",
    icon: "pi pi-calculator",
  },
  {
    group: "Analisis y Registros",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Actividad",
    routerLink: "/settings/user-activity-history",
    icon: "pi pi-chart-line",
  },
  {
    group: "Analisis y Registros",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Historial de ingresos",
    routerLink: "/report/access-history",
    icon: "pi pi-history",
  },
  {
    group: "Analisis y Registros",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Loggers Api",
    routerLink: "/settings/log-api-report",
    icon: "pi pi-file-edit",
  },
  {
    group: "Analisis y Registros",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Logs de Brevo",
    routerLink: "/settings/brevo-logs",
    icon: "pi pi-envelope",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Mini Postman",
    routerLink: "/settings/mini-postman",
    icon: "pi pi-send",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Demo UI ERP",
    routerLink: "/settings/demo-app",
    icon: "pi pi-desktop",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Reporte Datos Empleados",
    routerLink: "/settings/app-implementation-report",
    icon: "pi pi-users",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Design System & Guide",
    routerLink: "/settings/ui-catalog",
    icon: "pi pi-compass",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Depuracion",
    routerLink: "/settings/depuration",
    icon: "pi pi-cog",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "TestSignalR",
    routerLink: "/settings/testsignalr",
    icon: "pi pi-bolt",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Send Email",
    routerLink: "/settings/test-email",
    icon: "pi pi-envelope",
  },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Configuracion ElevenLabs",
    routerLink: "/settings/eleven-labs",
    icon: "pi pi-microphone",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(EApplicationRole.SuperUsuario),
    label: "Prueba de Inteligencia Artificial",
    routerLink: "/settings/ia-test",
    icon: "pi pi-bolt",
  },
];
