import { ApplicationRole } from "src/app/core/enums/asp-net-roles.enum";
import { AdminModuleGroup } from "./interfaces/admin-module-group.interface";

export const ADMIN_MODULES: AdminModuleGroup[] = [
  // -------------------------------------------------------------
  // SEGURIDAD Y PERMISOS
  // -------------------------------------------------------------
  {
    label: "Seguridad y Permisos",
    icon: "material-symbols-light:lock-outline",
    roles: [ApplicationRole.SuperUsuario],
    cards: [
      {
        title: "Clientes",
        description: "Gestión de clientes y condominios del sistema.",
        route: "/admin/customers",
        icon: "material-symbols-light:apartment",
        color: "#1d4ed8",
        bgColor: "#dbeafe",
      },
      {
        title: "Usuarios",
        description: "Administración de cuentas de usuario y accesos.",
        route: "/admin/user-accounts",
        icon: "material-symbols-light:person",
        color: "#1d4ed8",
        bgColor: "#dbeafe",
      },
      {
        title: "Roles",
        description: "Configuración de roles y permisos del sistema.",
        route: "/admin/roles",
        icon: "material-symbols-light:security",
        color: "#1d4ed8",
        bgColor: "#dbeafe",
      },
      {
        title: "Módulos",
        description: "Gestión de módulos disponibles en la aplicación.",
        route: "/admin/module-app",
        icon: "material-symbols-light:grid-view",
        color: "#1d4ed8",
        bgColor: "#dbeafe",
      },
      {
        title: "Módulos | Clientes",
        description: "Asignación de módulos por cliente.",
        route: "/admin/customer-module",
        icon: "material-symbols-light:grid-view",
        color: "#1d4ed8",
        bgColor: "#dbeafe",
      },
      {
        title: "Módulos | Roles",
        description: "Permisos de módulos por rol.",
        route: "/admin/module-app-role",
        icon: "material-symbols-light:key",
        color: "#1d4ed8",
        bgColor: "#dbeafe",
      },
      {
        title: "Jerarquía de Aprobación",
        description: "Reglas de aprobación por niveles.",
        route: "/admin/approval-rules",
        icon: "material-symbols-light:supervised-user-circle",
        color: "#1d4ed8",
        bgColor: "#dbeafe",
      },
      {
        title: "Matriz de Entrevistadores",
        description: "Asignación de entrevistadores por cliente y puesto.",
        route: "/admin/interviewer-matrix",
        icon: "material-symbols-light:supervised-user-circle",
        color: "#1d4ed8",
        bgColor: "#dbeafe",
      },
    ],
  },
  // -------------------------------------------------------------
  // CATÁLOGOS GENERALES
  // -------------------------------------------------------------
  {
    label: "Catálogos Generales",
    icon: "material-symbols-light:database-upload",
    roles: [ApplicationRole.SuperUsuario],
    cards: [
      {
        title: "Bancos",
        description: "Catálogo de instituciones bancarias.",
        route: "/admin/banks",
        icon: "material-symbols-light:account-balance",
        color: "#0e7490",
        bgColor: "#cffafe",
      },
      {
        title: "Forma de Pago",
        description: "Catálogo de formas de pago SAT.",
        route: "/admin/payment-method",
        icon: "material-symbols-light:credit-card",
        color: "#0e7490",
        bgColor: "#cffafe",
      },
      {
        title: "Método de Pago",
        description: "Catálogo de métodos de pago SAT.",
        route: "/admin/payment-type",
        icon: "material-symbols-light:wallet",
        color: "#0e7490",
        bgColor: "#cffafe",
      },
      {
        title: "Uso de CFDI",
        description: "Catálogo de usos de CFDI SAT.",
        route: "/admin/cfdi-use",
        icon: "material-symbols-light:receipt",
        color: "#0e7490",
        bgColor: "#cffafe",
      },
      {
        title: "Unidades de Medida",
        description: "Catálogo de unidades de medida SAT.",
        route: "/admin/units-of-measurement",
        icon: "material-symbols-light:tune",
        color: "#0e7490",
        bgColor: "#cffafe",
      },
      {
        title: "Fuentes de Reclutamiento",
        description: "Catálogo de canales/medios de reclutamiento.",
        route: "/admin/recruitment-sources",
        icon: "material-symbols-light:group",
        color: "#0e7490",
        bgColor: "#cffafe",
      },
      {
        title: "Catálogo de Documentos",
        description: "Documentos del expediente de empleados y candidatos.",
        route: "/admin/document-catalogs",
        icon: "material-symbols-light:description",
        color: "#0e7490",
        bgColor: "#cffafe",
      },
      {
        title: "Checklist de Onboarding",
        description: "Tareas, días SLA y roles aplicables por alta de personal.",
        route: "/admin/onboarding-checklist-options",
        icon: "material-symbols-light:fact-check",
        color: "#0e7490",
        bgColor: "#cffafe",
      },
      {
        title: "Horarios de Puesto",
        description: "Catálogo de turnos y horarios disponibles para puestos de trabajo.",
        route: "/admin/work-position-schedules",
        icon: "material-symbols-light:schedule",
        color: "#0e7490",
        bgColor: "#cffafe",
      },
    ],
  },
  // -------------------------------------------------------------
  // CATÁLOGOS DE TICKETS Y MANTENIMIENTO
  // -------------------------------------------------------------
  {
    label: "Catálogos de Tickets y Mantenimiento",
    icon: "material-symbols-light:home-repair-service",
    roles: [ApplicationRole.SuperUsuario],
    cards: [
      {
        title: "Categorías Ticket",
        description: "Categorías para clasificación de tickets.",
        route: "/admin/ticket-group-category",
        icon: "material-symbols-light:label",
        color: "#c2410c",
        bgColor: "#ffedd5",
      },
      {
        title: "Categoría Medidor",
        description: "Tipos de medidores para lecturas.",
        route: "/admin/meter-category",
        icon: "material-symbols-light:timer",
        color: "#c2410c",
        bgColor: "#ffedd5",
      },
      {
        title: "Categoría Productos",
        description: "Clasificación de productos de inventario.",
        route: "/admin/product-category",
        icon: "material-symbols-light:shopping-bag",
        color: "#c2410c",
        bgColor: "#ffedd5",
      },
      {
        title: "Clasificación Equipos",
        description: "Clasificación de maquinaria y equipos.",
        route: "/admin/machinery-classification",
        icon: "material-symbols-light:settings",
        color: "#c2410c",
        bgColor: "#ffedd5",
      },
      {
        title: "Entrega Recepción",
        description: "Catálogo de entrega y recepción.",
        route: "/admin/client-delivery-reception",
        icon: "material-symbols-light:group",
        color: "#c2410c",
        bgColor: "#ffedd5",
      },
      {
        title: "Calendario Maestro Mtto",
        description: "Planificación maestra de mantenimiento.",
        route: "/calendars/maintenance-master",
        icon: "material-symbols-light:calendar-today",
        color: "#c2410c",
        bgColor: "#ffedd5",
      },
      {
        title: "Calendario Maestro Clasificación",
        description: "Calendario por clasificación de equipos.",
        route: "/calendars/team-master-calendar",
        icon: "material-symbols-light:calendar-today",
        color: "#c2410c",
        bgColor: "#ffedd5",
      },
      {
        title: "Catálogo de Amenidades",
        description: "Gestión de amenidades del condominio.",
        route: "/admin/catalog-asset",
        icon: "material-symbols-light:star-outline",
        color: "#c2410c",
        bgColor: "#ffedd5",
      },
      {
        title: "Catálogo de Inspecciones",
        description: "Tipos de inspecciones disponibles.",
        route: "/admin/inspection-reviews-catalog",
        icon: "material-symbols-light:search",
        color: "#c2410c",
        bgColor: "#ffedd5",
      },
      {
        title: "Catálogo de Tareas",
        description: "Tareas recurrentes programadas.",
        route: "/recurring-tasks",
        icon: "material-symbols-light:article",
        color: "#c2410c",
        bgColor: "#ffedd5",
      },
    ],
  },
  // -------------------------------------------------------------
  // CONFIGURACIÓN DE SISTEMA
  // -------------------------------------------------------------
  {
    label: "Configuración de Sistema",
    icon: "material-symbols-light:settings-outline",
    roles: [ApplicationRole.SuperUsuario],
    cards: [
      {
        title: "Base de Conocimiento IA",
        description: "Gestión de conocimientos para asistente IA.",
        route: "/admin/ai-knowledge-base",
        icon: "material-symbols-light:auto-awesome-motion",
        color: "#4338ca",
        bgColor: "#e0e7ff",
      },
      {
        title: "Configuración Aspel",
        description: "Parámetros de integración con Aspel COI.",
        route: "/accounting/aspel-customer-empresa",
        icon: "material-symbols-light:settings",
        color: "#4338ca",
        bgColor: "#e0e7ff",
      },
      {
        title: "Sincronización Aspel",
        description: "Procesos de sincronización con Aspel.",
        route: "/accounting/aspel-sync",
        icon: "material-symbols-light:sync",
        color: "#4338ca",
        bgColor: "#e0e7ff",
      },
      {
        title: "Conciliación Juntas Mensuales",
        description: "Conciliación de actas de junta.",
        route: "/admin/monthly-meetings-reconciliation",
        icon: "material-symbols-light:link",
        color: "#4338ca",
        bgColor: "#e0e7ff",
      },
      {
        title: "Checklist Asamblea",
        description: "Plantillas de checklist para asambleas.",
        route: "/admin/assembly-checklist-catalog",
        icon: "material-symbols-light:fact-check",
        color: "#4338ca",
        bgColor: "#e0e7ff",
      },
      {
        title: "Vault de Secretos",
        description: "Gestión segura de secretos y credenciales.",
        route: "/admin/vault-secrets",
        icon: "material-symbols-light:key",
        color: "#4338ca",
        bgColor: "#e0e7ff",
      },
      {
        title: "Respaldo de BD",
        description: "Configuración de backups de base de datos.",
        route: "/admin/database-backup",
        icon: "material-symbols-light:database-upload",
        color: "#4338ca",
        bgColor: "#e0e7ff",
      },
      {
        title: "Jobs",
        description: "Gestión de trabajos programados.",
        route: "/admin/jobs",
        icon: "material-symbols-light:work",
        color: "#4338ca",
        bgColor: "#e0e7ff",
      },
      {
        title: "Catálogo de Tareas Recurrentes",
        description:
          "Plantillas de tareas recurrentes: criticidad, aviso previo y respaldo.",
        route: "/admin/recurring-task-catalog",
        icon: "material-symbols-light:event-repeat",
        color: "#4338ca",
        bgColor: "#e0e7ff",
      },
      {
        title: "Configuración ElevenLabs",
        description: "Parámetros de síntesis de voz IA.",
        route: "/admin/eleven-labs",
        icon: "material-symbols-light:mic",
        color: "#4338ca",
        bgColor: "#e0e7ff",
      },
    ],
  },
  // -------------------------------------------------------------
  // CONFIGURACIÓN DE CORREO ELECTRÓNICO
  // -------------------------------------------------------------
  {
    label: "Configuración de Correo Electrónico",
    icon: "material-symbols-light:mail-outline",
    roles: [ApplicationRole.SuperUsuario],
    cards: [
      {
        title: "Emails Corporativos",
        description: "Cuentas de correo por cliente.",
        route: "/admin/customer-data-company",
        icon: "material-symbols-light:mail-outline",
        color: "#be185d",
        bgColor: "#fce7f3",
      },
      {
        title: "Datos de Email",
        description: "Plantillas y configuración de envíos.",
        route: "/admin/email-data",
        icon: "material-symbols-light:mail-outline",
        color: "#be185d",
        bgColor: "#fce7f3",
      },
    ],
  },
  // -------------------------------------------------------------
  // RECURSOS HUMANOS
  // -------------------------------------------------------------
  {
    label: "Recursos Humanos",
    icon: "material-symbols-light:badge",
    roles: [ApplicationRole.SuperUsuario],
    cards: [
      {
        title: "Tipos de Incidencia",
        description: "Catálogo de tipos de incidencias laborales.",
        route: "/admin/incident-types",
        icon: "material-symbols-light:warning",
        color: "#0f766e",
        bgColor: "#ccfbf1",
      },
      {
        title: "Tipos de Sanción",
        description: "Catálogo de sanciones disciplinarias.",
        route: "/admin/sanction-types",
        icon: "material-symbols-light:article",
        color: "#0f766e",
        bgColor: "#ccfbf1",
      },
      {
        title: "Ajuste Balance Vacaciones",
        description: "Ajuste de saldos de vacaciones.",
        route: "/recursos-humanos/admin-balances-vacaciones",
        icon: "material-symbols-light:calculate",
        color: "#0f766e",
        bgColor: "#ccfbf1",
      },
    ],
  },
  // -------------------------------------------------------------
  // ANÁLISIS Y REGISTROS
  // -------------------------------------------------------------
  {
    label: "Análisis y Registros",
    icon: "material-symbols-light:monitoring",
    roles: [ApplicationRole.SuperUsuario],
    cards: [
      {
        title: "Auditoría de Cambios",
        description: "Historial de modificaciones en el sistema.",
        route: "/admin/audit-entries",
        icon: "material-symbols-light:note-alt",
        color: "#a16207",
        bgColor: "#fef9c3",
      },
      {
        title: "Actividad de Usuarios",
        description: "Registro de actividad y navegación.",
        route: "/admin/user-activity-history",
        icon: "material-symbols-light:monitoring",
        color: "#a16207",
        bgColor: "#fef9c3",
      },
      {
        title: "Historial de Ingresos",
        description: "Control de accesos al sistema.",
        route: "/report/access-history",
        icon: "material-symbols-light:history",
        color: "#a16207",
        bgColor: "#fef9c3",
      },
      {
        title: "Loggers API",
        description: "Logs de peticiones a la API.",
        route: "/admin/log-api-report",
        icon: "material-symbols-light:note-alt",
        color: "#a16207",
        bgColor: "#fef9c3",
      },
      {
        title: "Logs de Brevo",
        description: "Registros de envíos de email (Brevo).",
        route: "/admin/brevo-logs",
        icon: "material-symbols-light:mail-outline",
        color: "#a16207",
        bgColor: "#fef9c3",
      },
    ],
  },
  // -------------------------------------------------------------
  // HERRAMIENTAS DE DESARROLLO / PRUEBA
  // -------------------------------------------------------------
  {
    label: "Herramientas de Desarrollo/Prueba",
    icon: "material-symbols-light:science",
    roles: [ApplicationRole.SuperUsuario],
    cards: [
      {
        title: "Mini Postman",
        description: "Cliente HTTP para testing de endpoints.",
        route: "/admin/mini-postman",
        icon: "material-symbols-light:send",
        color: "#15803d",
        bgColor: "#dcfce7",
      },
      {
        title: "Reporte Datos Empleados",
        description: "Reporte de implementación por empleado.",
        route: "/admin/app-implementation-report",
        icon: "material-symbols-light:group",
        color: "#15803d",
        bgColor: "#dcfce7",
      },
      {
        title: "Design System & Guide",
        description: "Catálogo de componentes UI y guías.",
        route: "/admin/ui-catalog",
        icon: "material-symbols-light:explore",
        color: "#15803d",
        bgColor: "#dcfce7",
      },
      {
        title: "Depuración",
        description: "Herramientas de debugging y diagnóstico.",
        route: "/admin/depuration",
        icon: "material-symbols-light:settings",
        color: "#15803d",
        bgColor: "#dcfce7",
      },
      {
        title: "Test SignalR",
        description: "Pruebas de conectividad en tiempo real.",
        route: "/admin/testsignalr",
        icon: "material-symbols-light:bolt",
        color: "#15803d",
        bgColor: "#dcfce7",
      },
      {
        title: "Test Email",
        description: "Envío de correos de prueba.",
        route: "/admin/test-email",
        icon: "material-symbols-light:mail-outline",
        color: "#15803d",
        bgColor: "#dcfce7",
      },
      {
        title: "Prueba de IA",
        description: "Testing de modelos de inteligencia artificial.",
        route: "/admin/ai-test",
        icon: "material-symbols-light:bolt",
        color: "#15803d",
        bgColor: "#dcfce7",
      },
      {
        title: "Cotizador",
        description: "Calculadora de precios y cotizaciones.",
        route: "/admin/pricing-calculator",
        icon: "material-symbols-light:calculate",
        color: "#15803d",
        bgColor: "#dcfce7",
      },
      {
        title: "Conventions Guide",
        description: "Guía de convenciones del proyecto.",
        route: "/admin/conventions-guide",
        icon: "material-symbols-light:menu-book",
        color: "#15803d",
        bgColor: "#dcfce7",
      },
    ],
  },
];
