import { AspRoleService } from "src/app/core/auth/services/asp-role.service";
import { ApplicationRole } from "src/app/core/enums/asp-net-roles.enum";
import { SettingsMenuItem } from "src/app/core/interfaces/menu.interface";

export const settingMenu = (aspRoleS: AspRoleService): SettingsMenuItem[] => [
  {
    group: "Seguridad y Permisos",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Clientes",
    icon: "mdi:office-building",
    routerLink: "/admin/customers",
  },
  {
    group: "Seguridad y Permisos",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Usuarios",
    icon: "mdi:account",
    routerLink: "/admin/user-accounts",
  },
  {
    group: "Seguridad y Permisos",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Roles",
    routerLink: "/admin/roles",
    icon: "mdi:shield",
  },
  {
    group: "Seguridad y Permisos",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Modulos",
    routerLink: "/admin/module-app",
    icon: "mdi:grid",
  },
  {
    group: "Seguridad y Permisos",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Modulos | Clientes",
    routerLink: "/admin/customer-module",
    icon: "mdi:grid",
  },
  {
    group: "Seguridad y Permisos",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Modulos | Roles",
    routerLink: "/admin/module-app-role",
    icon: "mdi:key",
  },
  {
    group: "Seguridad y Permisos",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Jerarquia de Aprobacion",
    routerLink: "/admin/approval-rules",
    icon: "mdi:sitemap",
  },
  {
    group: "Catalogos Generales",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Bancos",
    routerLink: "/admin/banks",
    icon: "mdi:bank",
  },
  {
    group: "Catalogos Generales",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Forma de pago",
    routerLink: "/admin/payment-method",
    icon: "mdi:credit-card",
  },
  {
    group: "Catalogos Generales",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Metodo de pago",
    routerLink: "/admin/payment-type",
    icon: "mdi:wallet",
  },
  {
    group: "Catalogos Generales",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Uso de cfdi",
    routerLink: "/admin/cfdi-use",
    icon: "mdi:receipt",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Categorias ticket",
    routerLink: "/admin/ticket-group-category",
    icon: "mdi:tag",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Categoria Medidor",
    routerLink: "/admin/meter-category",
    icon: "mdi:stopwatch",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Categoria productos",
    routerLink: "/admin/product-category",
    icon: "mdi:shopping",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Clasificacion equipos",
    routerLink: "/admin/machinery-classification",
    icon: "mdi:cog",
  },
  {
    group: "Catalogos Generales",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Unidades de medida",
    routerLink: "/admin/units-of-measurement",
    icon: "mdi:tune",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Entrega Recepcion",
    routerLink: "/admin/client-delivery-reception",
    icon: "mdi:account-group",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Calendario maestro mtto",
    routerLink: "/calendars/maintenance-master",
    icon: "mdi:calendar",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Calendario maestro Clasificacion",
    routerLink: "/calendars/team-master-calendar",
    icon: "mdi:calendar",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Catalogo de amenidades",
    routerLink: "/admin/catalog-asset",
    icon: "mdi:star-outline",
  },
  // {
  //   group: "Catalogos de Tickets y Mantenimiento",
  //   visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
  //   label: "Catalogo de Permisos",
  //   routerLink: "/admin/request-types-list",
  //   icon: "mdi:pencil",
  // },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Catalogo de inspecciones",
    routerLink: "/admin/inspection-reviews-catalog",
    icon: "mdi:magnify",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Catalogo de tareas",
    routerLink: "/recurring-tasks",
    icon: "mdi:clipboard-text",
  },
  // {
  //   group: "Catalogos de Tickets y Mantenimiento",
  //   visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
  //   label: "Organigramas",
  //   routerLink: "/organization-chart/view",
  //   icon: "mdi:sitemap",
  // },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Base de Conocimiento IA",
    routerLink: "/admin/ai-knowledge-base",
    icon: "mdi:sparkles",
  },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Configuracion Aspel",
    routerLink: "/accounting/aspel-customer-empresa",
    icon: "mdi:cog",
  },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Sincronizacion Aspel",
    routerLink: "/accounting/aspel-sync",
    icon: "mdi:sync",
  },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Conciliacion juntas mensuales",
    routerLink: "/admin/monthly-meetings-reconciliation",
    icon: "mdi:link",
  },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Checklist asamblea",
    routerLink: "/admin/assembly-checklist-catalog",
    icon: "mdi:format-list-checks",
  },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Vault de Secretos",
    routerLink: "/admin/vault-secrets",
    icon: "mdi:shield-key",
  },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Respaldo de BD",
    routerLink: "/admin/database-backup",
    icon: "mdi:database-export",
  },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "jobs",
    routerLink: "/admin/jobs",
    icon: "mdi:briefcase",
  },
  {
    group: "Configuracion de Correo Electronico",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Emails corporativos",
    routerLink: "/admin/customer-data-company",
    icon: "mdi:email-outline",
  },
  {
    group: "Configuracion de Correo Electronico",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Datos de email",
    routerLink: "/admin/email-data",
    icon: "mdi:email-outline",
  },
  {
    group: "Recursos Humanos",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Tipos de incidencia",
    routerLink: "/admin/incident-types",
    icon: "mdi:alert",
  },
  {
    group: "Recursos Humanos",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Tipos de sancion",
    routerLink: "/admin/sanction-types",
    icon: "mdi:clipboard-text",
  },
  {
    group: "Recursos Humanos",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Ajuste balance",
    routerLink: "/recursos-humanos/admin-balances-vacaciones",
    icon: "mdi:calculator",
  },
  {
    group: "Analisis y Registros",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Auditoría de cambios",
    routerLink: "/admin/audit-entries",
    icon: "mdi:file-document-edit",
  },
  {
    group: "Analisis y Registros",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Actividad",
    routerLink: "/admin/user-activity-history",
    icon: "mdi:chart-line",
  },
  {
    group: "Analisis y Registros",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Historial de ingresos",
    routerLink: "/report/access-history",
    icon: "mdi:history",
  },
  {
    group: "Analisis y Registros",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Loggers Api",
    routerLink: "/admin/log-api-report",
    icon: "mdi:file-edit",
  },
  {
    group: "Analisis y Registros",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Logs de Brevo",
    routerLink: "/admin/brevo-logs",
    icon: "mdi:email-outline",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Mini Postman",
    routerLink: "/admin/mini-postman",
    icon: "mdi:send",
  },
  // {
  //   group: "Herramientas de Desarrollo/Prueba",
  //   visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
  //   label: "Demo UI ERP",
  //   routerLink: "/admin/demo-app",
  //   icon: "mdi:monitor",
  // },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Reporte Datos Empleados",
    routerLink: "/admin/app-implementation-report",
    icon: "mdi:account-group",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Design System & Guide",
    routerLink: "/admin/ui-catalog",
    icon: "mdi:compass",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Depuracion",
    routerLink: "/admin/depuration",
    icon: "mdi:cog",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "TestSignalR",
    routerLink: "/admin/testsignalr",
    icon: "mdi:lightning-bolt",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Send Email",
    routerLink: "/admin/test-email",
    icon: "mdi:email-outline",
  },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Configuracion ElevenLabs",
    routerLink: "/admin/eleven-labs",
    icon: "mdi:microphone",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Prueba de Inteligencia Artificial",
    routerLink: "/admin/ai-test",
    icon: "mdi:lightning-bolt",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Cotizador",
    routerLink: "/admin/pricing-calculator",
    icon: "mdi:calculator",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "📋 Conventions Guide",
    routerLink: "/admin/conventions-guide",
    icon: "mdi:book-open-variant",
  },
];
