import { AspRoleService } from "src/app/core/auth/services/asp-role.service";
import { ApplicationRole } from "src/app/core/enums/asp-net-roles.enum";
import { SettingsMenuItem } from "src/app/core/interfaces/menu.interface";

export const settingMenu = (aspRoleS: AspRoleService): SettingsMenuItem[] => [
  {
    group: "Seguridad y Permisos",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Clientes",
    icon: "material-symbols-light:apartment",
    routerLink: "/admin/customers",
  },
  {
    group: "Seguridad y Permisos",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Usuarios",
    icon: "material-symbols-light:person",
    routerLink: "/admin/user-accounts",
  },
  {
    group: "Seguridad y Permisos",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Roles",
    routerLink: "/admin/roles",
    icon: "material-symbols-light:security",
  },
  {
    group: "Seguridad y Permisos",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Modulos",
    routerLink: "/admin/module-app",
    icon: "material-symbols-light:grid-view",
  },
  {
    group: "Seguridad y Permisos",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Modulos | Clientes",
    routerLink: "/admin/customer-module",
    icon: "material-symbols-light:grid-view",
  },
  {
    group: "Seguridad y Permisos",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Modulos | Roles",
    routerLink: "/admin/module-app-role",
    icon: "material-symbols-light:key",
  },
  {
    group: "Seguridad y Permisos",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Jerarquia de Aprobacion",
    routerLink: "/admin/approval-rules",
    icon: "material-symbols-light:account-tree",
  },
  {
    group: "Seguridad y Permisos",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Matriz de Entrevistadores",
    routerLink: "/admin/interviewer-matrix",
    icon: "material-symbols-light:supervised-user-circle",
  },
  {
    group: "Catalogos Generales",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Bancos",
    routerLink: "/admin/banks",
    icon: "material-symbols-light:account-balance",
  },
  {
    group: "Catalogos Generales",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Forma de pago",
    routerLink: "/admin/payment-method",
    icon: "material-symbols-light:credit-card",
  },
  {
    group: "Catalogos Generales",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Metodo de pago",
    routerLink: "/admin/payment-type",
    icon: "material-symbols-light:wallet",
  },
  {
    group: "Catalogos Generales",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Uso de cfdi",
    routerLink: "/admin/cfdi-use",
    icon: "material-symbols-light:receipt",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Categorias ticket",
    routerLink: "/admin/ticket-group-category",
    icon: "material-symbols-light:label",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Categoria Medidor",
    routerLink: "/admin/meter-category",
    icon: "material-symbols-light:timer",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Categoria productos",
    routerLink: "/admin/product-category",
    icon: "material-symbols-light:shopping-bag",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Clasificacion equipos",
    routerLink: "/admin/machinery-classification",
    icon: "material-symbols-light:settings",
  },
  {
    group: "Catalogos Generales",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Unidades de medida",
    routerLink: "/admin/units-of-measurement",
    icon: "material-symbols-light:tune",
  },
  {
    group: "Catalogos Generales",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Fuentes de reclutamiento",
    routerLink: "/admin/recruitment-sources",
    icon: "material-symbols-light:group",
  },
  {
    group: "Catalogos Generales",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Catalogo de documentos",
    routerLink: "/admin/document-catalogs",
    icon: "material-symbols-light:description",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Entrega Recepcion",
    routerLink: "/admin/client-delivery-reception",
    icon: "material-symbols-light:group",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Calendario maestro mtto",
    routerLink: "/calendars/maintenance-master",
    icon: "material-symbols-light:calendar-today",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Calendario maestro Clasificacion",
    routerLink: "/calendars/team-master-calendar",
    icon: "material-symbols-light:calendar-today",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Catalogo de amenidades",
    routerLink: "/admin/catalog-asset",
    icon: "material-symbols-light:star-outline",
  },
  // {
  //   group: "Catalogos de Tickets y Mantenimiento",
  //   visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
  //   label: "Catalogo de Permisos",
  //   routerLink: "/admin/request-types-list",
  //   icon: "material-symbols-light:edit",
  // },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Catalogo de inspecciones",
    routerLink: "/admin/inspection-reviews-catalog",
    icon: "material-symbols-light:search",
  },
  {
    group: "Catalogos de Tickets y Mantenimiento",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Catalogo de tareas",
    routerLink: "/recurring-tasks",
    icon: "material-symbols-light:article",
  },
  // {
  //   group: "Catalogos de Tickets y Mantenimiento",
  //   visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
  //   label: "Organigramas",
  //   routerLink: "/organization-chart/view",
  //   icon: "material-symbols-light:account-tree",
  // },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Base de Conocimiento IA",
    routerLink: "/admin/ai-knowledge-base",
    icon: "material-symbols-light:auto-awesome-motion",
  },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Configuracion Aspel",
    routerLink: "/accounting/aspel-customer-empresa",
    icon: "material-symbols-light:settings",
  },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Sincronizacion Aspel",
    routerLink: "/accounting/aspel-sync",
    icon: "material-symbols-light:sync",
  },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Conciliacion juntas mensuales",
    routerLink: "/admin/monthly-meetings-reconciliation",
    icon: "material-symbols-light:link",
  },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Checklist asamblea",
    routerLink: "/admin/assembly-checklist-catalog",
    icon: "material-symbols-light:fact-check",
  },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Vault de Secretos",
    routerLink: "/admin/vault-secrets",
    icon: "material-symbols-light:key",
  },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Respaldo de BD",
    routerLink: "/admin/database-backup",
    icon: "material-symbols-light:database-upload",
  },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "jobs",
    routerLink: "/admin/jobs",
    icon: "material-symbols-light:work",
  },
  {
    group: "Configuracion de Correo Electronico",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Emails corporativos",
    routerLink: "/admin/customer-data-company",
    icon: "material-symbols-light:mail-outline",
  },
  {
    group: "Configuracion de Correo Electronico",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Datos de email",
    routerLink: "/admin/email-data",
    icon: "material-symbols-light:mail-outline",
  },
  {
    group: "Recursos Humanos",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Tipos de incidencia",
    routerLink: "/admin/incident-types",
    icon: "material-symbols-light:warning",
  },
  {
    group: "Recursos Humanos",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Tipos de sancion",
    routerLink: "/admin/sanction-types",
    icon: "material-symbols-light:article",
  },
  {
    group: "Recursos Humanos",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Ajuste balance",
    routerLink: "/recursos-humanos/admin-balances-vacaciones",
    icon: "material-symbols-light:calculate",
  },
  {
    group: "Analisis y Registros",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Auditoría de cambios",
    routerLink: "/admin/audit-entries",
    icon: "material-symbols-light:note-alt",
  },
  {
    group: "Analisis y Registros",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Actividad",
    routerLink: "/admin/user-activity-history",
    icon: "material-symbols-light:monitoring",
  },
  {
    group: "Analisis y Registros",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Historial de ingresos",
    routerLink: "/report/access-history",
    icon: "material-symbols-light:history",
  },
  {
    group: "Analisis y Registros",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Loggers Api",
    routerLink: "/admin/log-api-report",
    icon: "material-symbols-light:note-alt",
  },
  {
    group: "Analisis y Registros",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Logs de Brevo",
    routerLink: "/admin/brevo-logs",
    icon: "material-symbols-light:mail-outline",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Mini Postman",
    routerLink: "/admin/mini-postman",
    icon: "material-symbols-light:send",
  },
  // {
  //   group: "Herramientas de Desarrollo/Prueba",
  //   visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
  //   label: "Demo UI ERP",
  //   routerLink: "/admin/demo-app",
  //   icon: "material-symbols-light:desktop-windows",
  // },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Reporte Datos Empleados",
    routerLink: "/admin/app-implementation-report",
    icon: "material-symbols-light:group",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Design System & Guide",
    routerLink: "/admin/ui-catalog",
    icon: "material-symbols-light:explore",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Depuracion",
    routerLink: "/admin/depuration",
    icon: "material-symbols-light:settings",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "TestSignalR",
    routerLink: "/admin/testsignalr",
    icon: "material-symbols-light:bolt",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Send Email",
    routerLink: "/admin/test-email",
    icon: "material-symbols-light:mail-outline",
  },
  {
    group: "Configuracion de Sistema",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Configuracion ElevenLabs",
    routerLink: "/admin/eleven-labs",
    icon: "material-symbols-light:mic",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Prueba de Inteligencia Artificial",
    routerLink: "/admin/ai-test",
    icon: "material-symbols-light:bolt",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "Cotizador",
    routerLink: "/admin/pricing-calculator",
    icon: "material-symbols-light:calculate",
  },
  {
    group: "Herramientas de Desarrollo/Prueba",
    visible: aspRoleS.hasRole(ApplicationRole.SuperUsuario),
    label: "📋 Conventions Guide",
    routerLink: "/admin/conventions-guide",
    icon: "material-symbols-light:menu-book",
  },
];
