// Mantener sincronizado con api/LuxuryApp.Shared/Enums/Departament.cs.
// Si se agrega, elimina o reordena un valor aqui, actualizar tambien el enum del backend.
export enum Department {
  Administracion = 0,
  Legal,
  Contabilidad,
  Mantenimiento,
  Limpieza,
  Operaciones,
  Jardineria,
  Sistemas,
  Seguridad,
  Constructora,
  Supervision,
  Direcciones,
  RecursosHumanos,
  Reclutamiento,
  Recepcion,
  Mensajeria,
  Ludoteca,
  Almacen,
  Amenidades,
  Asistente,
  NA,
}
