export {
  CustomBtnActiveDesactive,
  CustomBtnActiveDesactive as CustomButtonActiveDesactive,
  CustomButtonAdd,
  CustomButtonConfirm,
  CustomButtonDelete,
  CustomButtonDownload,
  CustomButtonEdit,
  CustomButtonItem,
  CustomButtonSave,
  CustomButtonSendEmail,
  CustomButtonTracking,
  CustomButtonViewPdf,
  CustomButton,
} from "./web-buttons.impl";
