export const PRIME_TO_ICONIFY: Record<string, string> = {
  "angle-double-down": "mdi:chevron-double-down",
  "angle-double-up": "mdi:chevron-double-up",
  "angle-down": "mdi:chevron-down",
  "angle-right": "mdi:chevron-right",
  "angle-up": "mdi:chevron-up",
  "arrow-down": "mdi:arrow-down",
  "arrow-down-left": "mdi:arrow-down-left",
  "arrow-left": "mdi:arrow-left",
  "arrow-right": "mdi:arrow-right",
  "arrows-alt": "mdi:arrow-expand-all",
  "arrows-h": "mdi:arrow-expand-horizontal",
  "arrow-up": "mdi:arrow-up",
  "arrow-up-right": "mdi:arrow-up-right",
  "balance-scale": "mdi:scale-balance",
  ban: "mdi:ban",
  bars: "mdi:menu",
  bell: "mdi:bell",
  "bell-slash": "mdi:bell-off",
  bolt: "mdi:lightning-bolt",
  book: "mdi:book",
  "bookmark-fill": "mdi:bookmark",
  box: "mdi:package",
  briefcase: "mdi:briefcase",
  building: "mdi:office-building",
  "building-columns": "mdi:bank",
  calculator: "mdi:calculator",
  calendar: "mdi:calendar",
  "calendar-check": "mdi:calendar-check",
  "calendar-clock": "mdi:calendar-clock",
  "calendar-minus": "mdi:calendar-minus",
  "calendar-plus": "mdi:calendar-plus",
  "calendar-times": "mdi:calendar-remove",
  camera: "mdi:camera",
  "chart-bar": "mdi:chart-bar",
  "chart-line": "mdi:chart-line",
  check: "mdi:check",
  "check-circle": "mdi:check-circle",
  "check-square": "mdi:checkbox-marked",
  "chevron-down": "mdi:chevron-down",
  "chevron-left": "mdi:chevron-left",
  "chevron-right": "mdi:chevron-right",
  "chevron-up": "mdi:chevron-up",
  circle: "mdi:circle",
  "circle-fill": "mdi:circle",
  clipboard: "mdi:clipboard-text",
  clock: "mdi:clock-outline",
  clone: "mdi:content-copy",
  "cloud-upload": "mdi:cloud-upload",
  code: "mdi:code-tags",
  cog: "mdi:cog",
  comment: "mdi:comment",
  comments: "mdi:comment-multiple",
  compass: "mdi:compass",
  copy: "mdi:content-copy",
  "credit-card": "mdi:credit-card",
  desktop: "mdi:monitor",
  dollar: "mdi:dollar",
  download: "mdi:download",
  "ellipsis-h": "mdi:dots-horizontal",
  "ellipsis-v": "mdi:dots-vertical",
  envelope: "mdi:email-outline",
  eraser: "mdi:eraser",
  "exclamation-circle": "mdi:alert-circle",
  "exclamation-triangle": "mdi:alert",
  "external-link": "mdi:external-link",
  eye: "mdi:eye-outline",
  "eye-slash": "mdi:eye-off",
  file: "mdi:file-document-outline",
  "file-check": "mdi:file-check",
  "file-code": "mdi:file-code",
  "file-edit": "mdi:file-edit",
  "file-excel": "mdi:file-excel",
  "file-pdf": "mdi:file-pdf-box",
  "file-plus": "mdi:file-plus",
  "file-text": "mdi:file-text",
  "file-zip": "mdi:zip-box",
  filter: "mdi:filter-variant",
  "filter-slash": "mdi:filter-variant-remove",
  flag: "mdi:flag-outline",
  "flag-fill": "mdi:flag",
  folder: "mdi:folder",
  "folder-open": "mdi:folder-open",
  gift: "mdi:gift",
  globe: "mdi:globe",
  "graduation-cap": "mdi:graduation-cap",
  hammer: "mdi:hammer",
  hashtag: "mdi:pound",
  heart: "mdi:heart-outline",
  "heart-fill": "mdi:heart",
  history: "mdi:history",
  home: "mdi:home",
  hourglass: "mdi:hourglass",
  "id-card": "mdi:card-account-details",
  image: "mdi:image",
  images: "mdi:image-multiple",
  inbox: "mdi:inbox",
  info: "mdi:information-outline",
  "info-circle": "mdi:information",
  key: "mdi:key",
  "level-down-alt": "mdi:arrow-down-bold",
  lightbulb: "mdi:lightbulb",
  link: "mdi:link",
  list: "mdi:format-list-bulleted",
  "list-check": "mdi:format-list-checks",
  lock: "mdi:lock",
  "lock-open": "mdi:lock-open",
  "map-marker": "mdi:map-marker",
  microchip: "mdi:chip",
  microphone: "mdi:microphone",
  minus: "mdi:minus",
  "minus-circle": "mdi:minus-circle",
  mobile: "mdi:cellphone",
  "money-bill": "mdi:currency-usd",
  moon: "mdi:weather-night",
  palette: "mdi:palette",
  paperclip: "mdi:paperclip",
  pencil: "mdi:pencil",
  "pen-to-square": "mdi:square-edit-outline",
  percent: "mdi:percent",
  percentage: "mdi:percent",
  phone: "mdi:phone",
  play: "mdi:play",
  "play-circle": "mdi:play-circle",
  plus: "mdi:plus",
  "plus-circle": "mdi:plus-circle",
  print: "mdi:printer",
  "question-circle": "mdi:help-circle",
  receipt: "mdi:receipt",
  refresh: "mdi:refresh",
  replay: "mdi:replay",
  save: "mdi:content-save",
  search: "mdi:magnify",
  "search-plus": "mdi:magnify-plus",
  send: "mdi:send",
  server: "mdi:server",
  shield: "mdi:shield",
  "shopping-bag": "mdi:shopping",
  "shopping-cart": "mdi:cart",
  "sign-in": "mdi:login",
  "sign-out": "mdi:logout",
  sitemap: "mdi:sitemap",
  "sliders-h": "mdi:tune",
  "sort-amount-down": "mdi:sort-descending",
  sparkles: "mdi:sparkles",
  star: "mdi:star-outline",
  stop: "mdi:stop",
  stopwatch: "mdi:stopwatch",
  sun: "mdi:weather-sunny",
  sync: "mdi:sync",
  table: "mdi:table",
  tag: "mdi:tag",
  "th-large": "mdi:grid",
  "thumbs-up": "mdi:thumb-up",
  times: "mdi:close",
  "times-circle": "mdi:close-circle",
  "toggle-off": "mdi:toggle-switch-off-outline",
  "toggle-on": "mdi:toggle-switch",
  trash: "mdi:delete",
  undo: "mdi:undo",
  upload: "mdi:upload",
  user: "mdi:account",
  "user-edit": "mdi:account-edit",
  "user-minus": "mdi:account-minus",
  "user-plus": "mdi:account-plus",
  users: "mdi:account-group",
  verified: "mdi:verified",
  video: "mdi:video",
  "volume-up": "mdi:volume-high",
  wallet: "mdi:wallet",
  whatsapp: "mdi:whatsapp",
  "window-maximize": "mdi:window-maximize",
  wrench: "mdi:wrench",
};

export const ICONIFY_TO_PRIME: Record<string, string> = Object.fromEntries(
  Object.entries(PRIME_TO_ICONIFY).map(([prime, iconify]) => [iconify, prime]),
);

export function resolveToIconify(
  iconName: string | null | undefined,
  fallback = "mdi:cog",
): string {
  if (!iconName) return fallback;

  // Ya está en formato Iconify (ej. "mdi:account-group")
  if (iconName.startsWith("mdi:") || iconName.includes(":")) return iconName;

  // Limpiar formatos comunes de PrimeIcons y clases de CSS
  const cleanName = iconName
    .replace(/^icon-pi-/, "")
    .replace(/^pi pi-/, "")
    .replace(/^pi-/, "")
    .replace(/^pi /, "")
    .trim();

  // Si después de limpiar no queda nada, usar fallback
  if (!cleanName) return fallback;

  // Buscar en el mapeo explícito
  const mapped = PRIME_TO_ICONIFY[cleanName];
  if (mapped) return mapped;

  // Si no está mapeado, intentar usarlo como mdi:prefijo
  // Pero primero verificar si parece una clase de PrimeIcons no mapeada
  return `mdi:${cleanName}`;
}

export function resolveToPrime(
  iconifyName: string | null | undefined,
  fallback = "cog",
): string {
  if (!iconifyName) return fallback;
  if (iconifyName.startsWith("mdi:")) {
    return ICONIFY_TO_PRIME[iconifyName] ?? iconifyName.replace("mdi:", "");
  }
  return iconifyName;
}
